### ISSUE TITLE
Keycloak not working with Public Ip for Camunda and Form Flow

### ISSUE THREAD

**Issue by uzrnem** [AOT-Technologies/forms-flow-ai-deployment#29]
I did setup on server and for public ip integration with keycloak working.

![image](https://user-images.githubusercontent.com/20123106/208388057-fa022f0a-eed8-4810-8098-db4280a9b6c1.png)

Error in Keycloak container 
![image](https://user-images.githubusercontent.com/20123106/208388675-987b3850-844d-414a-a1e1-ef44fc648138.png)

**Comment by sreehari-aot** [comment]
@kiran-aot this is due to the SSL, right? @abhilash-aot

**Comment by sreehari-aot** [comment]
@uzrnem please find our Gitter community https://gitter.im/forms-flow-ai/community

**Comment by sabalalani** [comment]
Did you find its solution?

**Comment by sabalalani** [comment]
I am also facing this issue, Please let me know.

**Comment by uzrnem** [comment]
Not found any solution as of now, they are not following this repo for installation.

**Comment by sreehari-aot** [comment]
Known Issue. A hotfix is available with v5.1.0
